### ISSUE TITLE
Issue with TypeScript

### ISSUE THREAD

**Issue by rossmc** [ye-will/next-plugin-antd#2]
Thanks for the plugin :)

I get the following error when I run `yarn build`.  It seems to be because I'm using TypeScript.

Any idea how to fix it?  Thanks

```
Failed to compile.

/proj/components/Logo/index.tsx
/proj//components/Logo/index.tsx(1,20):
1:20 Cannot find module './logo.module.less' or its corresponding type declarations.
  > 1 | import styles from './logo.module.less';
      |                    ^
    2 | 
    3 | export default function Logo(): JSX.Element {
    4 |   return (


> Build error occurred
Error: > Build failed because of webpack errors
```

**Comment by ye-will** [comment]
Try to add these lines into the file `next-env.d.ts`.

```typescript
declare module '*.less' {
  const resource: {[key: string]: string};
  export = resource;
}
```

**Comment by rossmc** [comment]
Thanks, That worked :)

I also found that just `declare module '*.less';` worked too. Do you know the difference?

Again this is a great plugin for next & antd, thanks again 💯

**Comment by ye-will** [comment]
> Thanks, That worked :)
> 
> I also found that just `declare module '*.less';` worked too. Do you know the difference?
> 
> Again this is a great plugin for next & antd, thanks again 💯

If you just `declare module '*.less';`, type checker/hint will fail. So the type of `styles` will be `any`

```typescript
import styles from './logo.module.less'; // => any
```

With the full declaration, the type of `styles` will be a object with `key: string` and `value: string`

```typescript
import styles from './logo.module.less'; // => {[key: string]: string}
```
