### ISSUE TITLE
Support for global styles?

### ISSUE THREAD

**Issue by rossmc** [ye-will/next-plugin-antd#3]
Hi,

Have you found a way to support global styles?

Out-of-the-box next.js supports them for CSS & SASS:    
https://nextjs.org/docs/basic-features/built-in-css-support#adding-a-global-stylesheet

But every-way I have tried with LESS, the global styles I add to _app.js are scoped with cssModules. The only work-around I could find was to use attribute selectors to avoid cssModules from scoping them.
![Screenshot 2020-06-24 at 19 01 33](https://user-images.githubusercontent.com/2452991/85600031-60bda600-b64d-11ea-8cbc-3c76e8bb93f9.png)

Is there anyway to only enable cssModules only for files ending in `module.less`?  
This is how next.js handles it.
> Important: To use CSS Modules, the CSS file name must end with .module.css.
> https://nextjs.org/learn/basics/assets-metadata-css/layout-component

**UPDATE**

On reading the [webPack cssLoader doc](https://github.com/webpack-contrib/css-loader#scope) I believed the following two approaches should work...
```javascript
module.exports = withPluginAntd({
  // loading custom ant design theme vars
  antdThemeVariables: themeVariables,
  // any options for @zeit/next-less
  cssModules: true,
  cssLoaderOptions: {
    // Automatically enable css modules for files satisfying `/\.module\.\w+$/i` RegExp.
    modules: { auto: true }
  }
});
```
```javascript
module.exports = withPluginAntd({
  // loading custom ant design theme vars
  antdThemeVariables: themeVariables,
  // any options for @zeit/next-less
  cssModules: true,
  cssLoaderOptions: {
    modules: {
      mode: (resourcePath) => {
        if (/module.less$/i.test(resourcePath)) {
          return 'local';
        }

        return 'global';
      }
    }
  }
});
```

Also tried this variation...
```javascript
module.exports = withPluginAntd({
  // loading custom ant design theme vars
  antdThemeVariables: themeVariables,
  // any options for @zeit/next-less
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: '[local]___[hash:base64:5]',
    mode: (resourcePath) => {
      if (/module.less$/i.test(resourcePath)) {
        return 'local';
      }

      return 'global';
    }
  }
});
```

They didn't work unfortunately, could it be a bug, I found in the debugger that the configuration was passed.
![Screenshot 2020-06-25 at 05 12 25](https://user-images.githubusercontent.com/2452991/85649135-980a7200-b6a2-11ea-9f9e-fc606d0edc9a.png)

Thanks

**Comment by rossmc** [comment]
I found  a workaround for it...
```
:global(.some-selector) {
  background-color: rebeccapurple;
}
```

**Comment by rossmc** [comment]
This may be related to this issue....
https://github.com/vercel/next-plugins/issues/641

**Comment by ye-will** [comment]
There are two options to generate `global` styles.

1. Set `cssModules: false` when initiating the plugin, that will disable css module and make all css styles `global`.

    ```javascript
    module.exports = withPluginAntd({
      // loading custom ant design theme vars
      antdThemeVariables: themeVariables
    });
    ```

    *You must handle selector names carefully to avoid naming conflict across different components.*

2. Use `:global` switcher to make a block global as what you have done. Addition infos for CSS-Module can be found [here](https://github.com/css-modules/css-modules#exceptions).

**Comment by rossmc** [comment]
Thanks

Yes, I will use the second option as I plan to use cssModules mostly, but sometimes there is a case for global css.

For option 1, it should be possible to use both configure both the use of cssModules and global styles for LESS.  But it seems to be a bug with @zeit/next-less (https://github.com/ye-will/next-plugin-antd/issues/3#issuecomment-649192768).

Option 2, is a good alternative.  Thanks again :)
