### ISSUE TITLE
chunk styles [mini-css-extract-plugin] Conflicting order betwee

### ISSUE THREAD

**Issue by rossmc** [ye-will/next-plugin-antd#4]
Hi,

I found I kept getting erros like the below...
```
warn  - chunk styles [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/@zeit/next-css/node_modules/css-loader??ref--6-2!./node_modules/less-loader/dist/cjs.js??ref--6-3!./node_modules/antd/lib/typography/style/index.less
 * css ./node_modules/@zeit/next-css/node_modules/css-loader??ref--6-2!./node_modules/less-loader/dist/cjs.js??ref--6-3!./node_modules/antd/lib/button/style/index.less
```

But changing `.babelrc` to 
```
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "import", {
        "libraryName": "antd",
        "style": false
      }
    ]
  ]
}
```
and importing LESS files in _app.tsx **fixed it**
```
import 'antd/dist/antd.less';
import '../styles/global.less';

import { AppProps } from 'next/app';
import React from 'react';

import AppWrapper from '../components/AppWrapper';
import { wrapper } from '../store';

const WrappedApp: React.FC<AppProps> = ({ Component, pageProps }: AppProps) => (
  <AppWrapper>
    <Component {...pageProps} />
  </AppWrapper>
);

export default wrapper.withRedux(WrappedApp);
```

I wonder, is this a better approach?

**Comment by rossmc** [comment]
hmm, actually I see the method I used above actually increases the amount of CSS loaded on the page.

**FROM:**
![Screenshot 2020-07-06 at 13 42 25](https://user-images.githubusercontent.com/2452991/86589766-8d978480-bf8e-11ea-9474-4c11adfe29dc.png)

**TO:**
![Screenshot 2020-07-06 at 13 40 03](https://user-images.githubusercontent.com/2452991/86589774-92f4cf00-bf8e-11ea-9d88-6d0f74c350ac.png)

How should these errors be handled?  Or is this just a bug in Antd?

**Comment by ye-will** [comment]
Please provide some additional info to me, such as the version of next.js and antd.

With your `FIX`, all antd styles was bundled, so the size of CSS increased a lot.

**Comment by ye-will** [comment]
Btw, `DO NOT` import any less file for ant-design component manually in your project, `.babelrc` will handle that work. Maybe that leads your conflicts.

**Comment by rossmc** [comment]
> Please provide some additional info to me, such as the version of next.js and antd.

I was able to reproduce by installing with:
```
yarn create next-app -e https://github.com/ye-will/next-plugin-antd/tree/master/examples/with-ant-design-less with-ant-design-less
```

And adding the two pages below to the `pages/` directory...

`pages/page1.js`
```
import {
  BarChartOutlined
} from '@ant-design/icons';
import { Button, DatePicker, Typography } from 'antd';
import Link from 'next/link'

export default () => {
  const { Title } = Typography;
  return (
    <div>
      <div>
        <Link href="/page2">
          <a style={{ display: 'inline-block', margin: '10px ' }}>Page 2</a>
        </Link>
        <Link href="/">
          <a style={{ display: 'inline-block', margin: '10px ' }}>Home</a>
        </Link>
      </div>
      <Button type="primary" style={{ margin: '20px 0' }}>
        Primary Button
      </Button>
      <Title level={3} style={{ margin: '20px 0' }}>
        <BarChartOutlined />
        <a href="https://ant.design/components/icon/">Icons</a>
      </Title>
      <DatePicker
        style={{ margin: '20px 0' }}
      />
      <DatePicker
        style={{ margin: '20px 0' }}
      />
      <Title level={4} style={{ margin: '20px 0' }}>
        This is a title Page 1
      </Title>
    </div>
  )
}
```


`pages/page2.js`

```
import { Button, DatePicker, Typography } from 'antd';
import Link from 'next/link'

export default () => {
  const { Title } = Typography;
  return (
    <div>
      <div>
        <Link href="/page1">
          <a style={{ display: 'inline-block', margin: '10px ' }}>Page 1</a>
        </Link>
        <Link href="/">
          <a style={{ display: 'inline-block', margin: '10px ' }}>Home</a>
        </Link>
      </div>
      <Button type="primary" style={{ margin: '20px 0' }}>
        Primary Button Page 2
      </Button>
      <DatePicker
        style={{ margin: '20px 0' }}
      />
      <Title level={4} style={{ margin: '20px 0' }}>
        This is a title Page 2
      </Title>
    </div>
  )
}
```

![Screenshot 2020-07-07 at 15 41 42](https://user-images.githubusercontent.com/2452991/86790154-5f867300-c068-11ea-990a-5231c7f57e37.png)

This seems to be a common issue with Antd, i.e. https://github.com/ant-design/ant-design/issues/15696

**Comment by ye-will** [comment]
Thanks for your example. It's a common issue related to style lazy loading, which both antd and next.js(or other framework) were trying to manage. Your can ignore the warning if your styles works.
I will find some ways to fix that later.

**Comment by ye-will** [comment]
Upgrade to [next-plugin-antd@0.1.2](https://www.npmjs.com/package/next-plugin-antd) will get rid of it.
Not really fixed, just mute that warnings with antd...

**Comment by rossmc** [comment]
> Upgrade to [next-plugin-antd@0.1.2](https://www.npmjs.com/package/next-plugin-antd) will get rid of it.
> Not really fixed, just mute that warnings with antd...

That worked nicely, thanks :)
