### ISSUE TITLE
0.2.0版本报错

### ISSUE THREAD

**Issue by HerbertHe** [ye-will/next-plugin-antd#8]
- antd 4.5.2

问题描述：

升级了antd的版本之后，也把插件升级到了0.2.0，但是报错了`Inline JavaScript is not enabled. Is it set in your options?`，还有lessLoaderOptions不匹配的问题。lessLoaderOptions这个改掉配置项就好了，但inline javascript的问题没能解决，就算手动开启了也无济于事。

可能的问题：

我去了antd官网搜配置项看了0.2.0版本的依赖和0.1.2版本依赖的区别，发现可能是less-loader的版本的问题！回退到0.1.2版本之后问题消失了。

我在antd的示例配置里面看到了`如果使用less-loader@5，请移除 lessOptions 这一级直接配置选项`这句话，不知道是否是这个问题
<https://ant.design/docs/react/customize-theme-cn>

**Comment by ye-will** [comment]
从 ant-design 4 开始，如果配合 less-loader < 6.0.0 来加载样式，可能出现一些异常显示。。。解决的唯一办法就是将 less-loader 升级到 6.0.0，但是 less-loader@6 和 less-loader@5 在配置上有 break change，所以如果你手动调整了 less-loader 的配置，需要自行更新配置。。。

例如，使用 0.1.2 版本时，next.config.js ：

```javascript
module.exports = withPluginAntd({
  antdThemeVariables: themeVariables,
  lessLoaderOptions: {
    javascriptEnabled: true
  },
})
```

在 0.2.0 版本中，应该为：

```javascript
module.exports = withPluginAntd({
  antdThemeVariables: themeVariables,
  lessLoaderOptions: {
    lessOptions: {
       javascriptEnabled: true
    }
  }
})
```

**Comment by HerbertHe** [comment]
哦哦，原来是这样，我刚在antd配置中也发现了这个问题
